paths:
  /home/1:
    get:
      summary: "get all products paginated"
      tags:
        - Products
      responses:
        "200":
          description: "successfully obtained all products"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: "error getting products"
  /productManager:
    get:
      summary: "functions to create products"
      tags:
        - Products
      responses:
        "200":
          description: "successfully created"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: "error creating product"
  /productManager/delete:
    put:
      summary: "delete product"
      responses:
        "200":
          description: "successfully deleted"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/deleteProduct"
        "500":
          description: "ID not found"
      tags:
        - Products
      parameters:
        - name: pid
      required: true
      description: product ID
      schema:
        $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deleteProduct"
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: String
          description: ID generated by MongoDB
        prod_name:
          type: String
          description: product name
        description:
          type: String
          description: product description
        stock:
          type: Number
          description: product stock
        price:
          type: Number
          description: product price
        prod_img:
          type: String
          default: product image
        owner:
          type: String
      example:
        _id: ObjectId(020323089j2a2ad24)
        prod_name: Iphone 14
        description: red, 128gb
        stock: 20
        price: 1500
        prod_img: "iphone.png"
  requestBodies:
    deleteProduct:
      type: object
      properties:
        _id:
          type: String
          description: ID generated by MongoDB
      example:
        _id: ObjectId(020323089j2a2ad24)
